# _config.yml

# required, replace with your own information -----
title: Stephen Akwaowo
author: Stephen Akwaowo
description: > 
  Stephen Akwaowo | Rawls College of Business, Texas Tech University | stephen.akwaowo@ttu.edu
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

